insert into table1 (COLUMN1, LONG_TEXT_COLUMN2, LONG_TEXT_COLUMN3, LONG_TEXT_COLUMN4, LONG_TEXT_COLUMN5,
LONG_TEXT_COLUMN6, LONG_TEXT_COLUMN7)
values (VALUE1, VALUE2, VALUE3, VALUE4, VALUE5, VALUE6, VALUE7);